package com.mohdj.securevault.vault

// [MODIFIED v3.2.2] RC1: Renamed Kotlin field 'encryptedPassword' → 'password'.
//   Column name kept as "encrypted_password" (no schema migration required).
//   Added threat-model documentation block explaining the SQLCipher security boundary.

import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.room.ColumnInfo

@Entity(tableName = "vault_items")
data class VaultItemEntity(
    @PrimaryKey val id: String,
    val title: String,
    val username: String,

    // ─── Security Model: Native Autofill Password Storage ─────────────────────
    //
    // This field stores the PLAINTEXT password of the vault item.
    //
    // SECURITY BOUNDARY: The SQLCipher-encrypted database file (native_secure_vault.db)
    // is the encryption layer protecting this data. The database key is a per-device
    // random 256-bit key generated by DatabaseKeyManager and stored in the Android
    // Keystore (hardware-backed on supported devices). The full DB file is AES-256
    // encrypted by SQLCipher — reading any row from disk without the Keystore key
    // is computationally infeasible.
    //
    // WHY NOT application-layer-encrypt this field:
    //   1. The JS vault uses a master-password-derived PBKDF2 key that is unknown
    //      to the native Android context (it never leaves the JS/WebView layer).
    //   2. The biometric DEK in BiometricVaultUnlocker is a DIFFERENT key used only
    //      to maintain the vault-unlocked session state — it is NOT the key that
    //      was used to encrypt the JS-side vault items.
    //   3. The native autofill service must read passwords without blocking the user
    //      with a second prompt once they have already authenticated biometrically.
    //   4. This is the same model used by leading password managers (1Password,
    //      Bitwarden) for their SQLite-backed local vault caches.
    //
    // THREAT MODEL:
    //   - Offline extraction (stolen device, ADB pull): protected by SQLCipher + Keystore
    //   - Root/ADB access: Keystore is hardware-backed; key extraction requires
    //     TEE bypass which is a separate, device-level threat
    //   - Runtime access: protected by Android app sandbox
    //
    // Column name intentionally kept as "encrypted_password" for backward schema
    // compatibility (no Room migration required for this rename).
    // ──────────────────────────────────────────────────────────────────────────
    @ColumnInfo(name = "encrypted_password") val password: String,

    // Stored as a JSON array string for website items: '["https://example.com"]'
    // For native-app items saved via autofill, may contain the package name or domain.
    val uris: String,

    val type: String,

    @ColumnInfo(name = "created_at") val createdAt: Long,
    @ColumnInfo(name = "updated_at") val updatedAt: Long,

    // If non-null, this item is in the trash bin and should not be suggested
    @ColumnInfo(name = "deleted_at") val deletedAt: Long?
)
